### ISSUE TITLE
Настройки: стоимость доставки в домашнем регионе может быть 0

### ISSUE THREAD

**Issue by lustmordtheblackpost** [yandex-money/yandex-money-ycms-v2-webasyst#12]
Сейчас при установке "Стоимость доставки в домашнем регионе" = 0, получаем ошибку "Не заполнена цена". Однако доставка в домашнем регионе может быть бесплатной

**Comment by ostulov** [comment]
Спасибо за описание ошибки. Мы рассмотрим возможность ее исправления.
Настройки модуля при возникновении такого сообщения сохраняются.

**Comment by ostulov** [comment]
Мы выпустили новую версию модуля v1.1.0, в которой настройки для задания стоимости доставки изменены.
Таким образом описанная Вами ошибка не должна более возникать.
