### ISSUE TITLE
Нет возможности удалить заказ, если оплата не прошла.

### ISSUE THREAD

**Issue by vicacid** [yandex-money/yandex-money-ycms-v2-webasyst#15]
Невозможно удалить заказ если отсутствует payment_id.

В логах 
`data: Failed to cancel payment: Payment can not be canceled in current status.Error code: invalid_request.Parameter name: payment_id.`

**Comment by ostulov** [comment]
Добрый день!

Напишите нам на почту cms@yamoney.ru с болле детальным описанием проблемы:
- опишите действия, которые выполняются для воспроизведения ошибки
- пришлите скриншоты настроек платежного модуля
- укажите информацию о платеже, с которым возникает эта проблема

**Comment by vicacid** [comment]
Fixed
