### ISSUE TITLE
Нет ни одного товара, после последнего обновления модуля

### ISSUE THREAD

**Issue by lustmordtheblackpost** [yandex-money/yandex-money-ycms-v2-webasyst#17]
![image](https://user-images.githubusercontent.com/20439994/46524281-fbca8700-c890-11e8-86b5-6b8390c1c9d1.png)

![image](https://user-images.githubusercontent.com/20439994/46524354-392f1480-c891-11e8-8bbb-3e33cd014605.png)

**Comment by ostulov** [comment]
Необходимо проверить в модуле условия выгрузки товаров. Возможно одно из условий не позволяет выгрузить товары.

**Comment by ostulov** [comment]
Если включен произвольный формат формирования прайс-листа, то проверьте, что в настройках товаров указан производитель. Либо переключите на упрощенный формат.
