### ISSUE TITLE
Невозможно получить статус оплаты

### ISSUE THREAD

**Issue by vicacid** [yandex-money/yandex-money-ycms-v2-webasyst#18]
При попытке получить информацию о заказе в административной пfнели (request - https://domain.com/webasyst/shop/?module=order&id=913&state_id=new|processing|paid) сервер отвечает с 500 ошибкой. В логах:
PHP Fatal error:  Call to a member function getType() on a non-object in /var/www/app/wa-apps/shop/plugins/yamodule_api/lib/shopYamodule_api.plugin.php on line 641
Судя по всему объект $paymentMethod пустой.

**Comment by ostulov** [comment]
Уточните, какая версия модуля у Вас используется?

**Comment by vicacid** [comment]
Устранено в новой версии.
